### ISSUE TITLE
Unable to make fork private.

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E-mcdp#3]
When I create a fork of the repository and try to change the access to private under _Settings/Access/Collaborators/Public Repository/Manage_, the button _Change visibility_ in the _Danger Zone_ is greyed out with the comment:

> Change repository visibility
> For security reasons, you cannot change the visibility of a fork.

**Comment by linusschoch** [comment]
Same for the repo [https://github.com/ACT4E/ACT4E-mcdp-exercise-template](url)

**Comment by AndreaCensi** [comment]
known limitation of github
